### ISSUE TITLE
Subscribe for new messages

### ISSUE THREAD

**Issue by Almeonamy** [ilyalatt/Telega#20]
Hi. How to subscribe for receiving new messages from Telegram (without creating requests each 500ms)?

**Comment by ilyalatt** [comment]
Hi. An issue for that is already created #15. I am going to implement it today.

**Comment by ilyalatt** [comment]
@Almeonamy you can try to use 3.2.0-preview001, you can see an example [here](https://github.com/ilyalatt/Telega/blob/master/Telega.Example/Program.cs#L148).
