### ISSUE TITLE
Connecting with Stored Sessions

### ISSUE THREAD

**Issue by wasimjee** [ilyalatt/Telega#26]
How can we connect using stored sessions from session.dat file

for 

`await TelegramClient.Connect()`

**Comment by ilyalatt** [comment]
You can use `await TelegramClient.Connect(ApiId, new FileSessionStore("session_file_name"))` for multiple accounts.
If you need a different way to work with sessions, you can implement custom `ISessionStore` (`Load` and `Save` methods) and pass it instead of `FileSessionStore`.

**Comment by wasimjee** [comment]
Thanks done
