### ISSUE TITLE
Unable to fetch from _tag

### ISSUE THREAD

**Issue by wasimjee** [ilyalatt/Telega#27]
Hi,

Thanks for earlier helps.

i am using this code

`var FullUser = await TLClient.Call(new GetFullUser(new InputUser.SelfTag()));`

now how to get the user details only, so that I can access the username, and phone, etc

**Comment by wasimjee** [comment]
Its done through AssertSome().

**Comment by ilyalatt** [comment]
Yeah, Telegram API scheme is clumsy sometimes. BTW I recommend you to read my [short introduction](https://github.com/ilyalatt/Telega/wiki/Introduction) to LanguageExt.
