### ISSUE TITLE
Updates without disconnect

### ISSUE THREAD

**Issue by wasimjee** [ilyalatt/Telega#29]
I am able to get the updates.

But after a few hours the system not getting updates.

It seems the system gets disconnected.

How can we check regularly if the system is still connected or if the systems get disconnected, then any events to generate

**Comment by ilyalatt** [comment]
Yes, it gets disconnected sometimes. The workaround is to send Ping request periodically. Telega tries to reconnect on every call if the client is disconnected. So it should help.
This problem is in the list of issues. Try to apply the workaround. If it is not sufficient I can work on in on the weekends.

**Comment by wasimjee** [comment]
Thanks @ilyalatt , i used the periodically ping, and its working. I mean its not disconnected yet

**Comment by kuriel07** [comment]
hi, sending ping worked for text message, but when the observer received message with link (or sometimes picture), the system get disconnected immdtly

**Comment by ilyalatt** [comment]
@kuriel07 Hi. Do you mean that any message containing link breaks further updates?

**Comment by kuriel07** [comment]
yes

> @kuriel07 Hi. Do you mean that any message containing link breaks further updates?

**Comment by ilyalatt** [comment]
@kuriel07 Hi. Sorry, it was a lie to myself. I am too exhausted to work on Telega for now. However I can help you if you want to fix the issue.

**Comment by ilyalatt** [comment]
I've opened new issue #62

**Comment by derodevil** [comment]
Has it been solved?
