### ISSUE TITLE
Get Notification on Channel Join

### ISSUE THREAD

**Issue by wasimjee** [ilyalatt/Telega#36]
Hi,

Is there any option for events so that I can get the info regarding any user who joins my channel or leaves my channel.

I am the owner of that channel

**Comment by ilyalatt** [comment]
Hi! To listen updates you need to use the code like [this](https://github.com/ilyalatt/Telega/blob/master/Telega.Example/Program.cs#L198). Looks like you're interested in the following tags `Update.ChatParticipantAddTag`, `Update.ChatParticipantDeleteTag`, `Update.ChatParticipantsTag`.

P.S. I plan to simplify the library a lot. Updates listening will be much simpler to.

**Comment by wasimjee** [comment]
> Hi! To listen updates you need to use the code like [this](https://github.com/ilyalatt/Telega/blob/master/Telega.Example/Program.cs#L198). Looks like you're interested in the following tags `Update.ChatParticipantAddTag`, `Update.ChatParticipantDeleteTag`, `Update.ChatParticipantsTag`.
> 
> P.S. I plan to simplify the library a lot. Updates listening will be much simpler to.

Thanks for your message.

But I am unable to get the updates when any user joins my channel.

can you just provide a sample code please, so that I can test
