### ISSUE TITLE
Calling GetAdminLog()

### ISSUE THREAD

**Issue by wasimjee** [ilyalatt/Telega#37]
Hi,

I am trying but unable to get, please can you help

**Comment by ilyalatt** [comment]
Hi. Can you describe the problem in the details? `Functions.Channels.GetAdminLog` has `Q` (I guess it is a search query so you can leave it empty), `MaxId`, `MinId` and `Limit` for pagination (you can set them to zero), and `Channel`. To find the channel you can use code like

```csharp
var contacts = await tg.Contacts.Search("https://t.me/durov");
var channel = contacts.Chats.Choose(Chat.AsChannelTag).HeadOrNone().IfNone(() => throw new Exception("A channel is not found"));
var channelPeer = new InputPeer.ChannelTag(
    channelId: channel.Id,
    accessHash: channel.AccessHash.AssertSome()
);
```
