### ISSUE TITLE
Type conversion between MessageMedia and InputMedia

### ISSUE THREAD

**Issue by tarasverq** [ilyalatt/Telega#39]
Hello!

I'm trying to use method [messages.sendMultiMedia](https://core.telegram.org/method/messages.sendMultiMedia) via Telega.

Firstly I've made a method _UploadMediaAsPhoto_  inside _TelegramClientMessages_ class.

```
public async Task<MessageMedia> UploadMediaAsPhoto(Some<InputPeer> peer,
            Some<InputFile> file,
            Option<Arr<InputDocument>> stickers,
            Option<int> ttlSeconds) =>
            await _tg.Call(func: new UploadMedia(
                peer: peer,
                media: new InputMedia.UploadedPhotoTag(
                    file: file,
                    stickers: stickers,
                    ttlSeconds: ttlSeconds
                )));
```

This method upload a file and associate it to a chat (without actually sending it to the chat). The result of this method is MessageMedia.

Now i should send it to telegram via `InputSingleMedia` wrapper.
**My question is how to convert `MessageMedia` to `InputMedia` which needs for constructor of type `InputSingleMedia`?**

My example code
```
static async Task SendMultiMedia(TelegramClient tg)
{
    const string photoUrl = "https://cdn1.img.jp.sputniknews.com/images/406/99/4069980.png";
    var photoName = Path.GetFileName(path: photoUrl);
    var photo = new WebClient().DownloadData(address: photoUrl);

    InputFile? tgPhoto = await tg.Upload.UploadFile(name: photoName, fileLength: photo.Length, stream: new MemoryStream(buffer: photo));
    InputPeer.SelfTag? peer = new InputPeer.SelfTag();
    
    MessageMedia? sentImage = await tg.Messages.UploadMediaAsPhoto(
        peer: peer,
        file: tgPhoto,
        stickers: Option<Arr<InputDocument>>.None,
        ttlSeconds: Option<int>.None);
    
    SendMultiMedia request = new SendMultiMedia(
        silent: false,
        background: false,
        clearDraft: false,
        peer: peer,
        replyToMsgId: Option<int>.None,
        multiMedia: new Arr<InputSingleMedia>()
        {
            new InputSingleMedia(
                media: sentImage.AsPhotoTag(),  <-- The problem is here
                randomId: Int64.MaxValue, 
                message: "", 
                entities: Option<Arr<MessageEntity>>.None)
        }, scheduleDate: Option<int>.None

    );
}
```

You can try it via [my fork](https://github.com/tarasverq/Telega/tree/75c3a854b2842a447feeed4d54c6a5d4b36c6917)

Thanks in advance!

**Comment by ilyalatt** [comment]
Hello. You need to pass `InputMedia.PhotoTag` to `media`. So you need `InputPhoto` as `id` for this, and there is `InputPhoto.Tag` that needs `Id`, `AccessHash`, `FileReference`. You can get them from `MessageMedia.PhotoTag`. It contains `Photo`, and you need to extract `Photo.Tag` from it. And this record should contain needed fields.
Pretty tangled puzzle from Telegram devs as always :)

**Comment by tarasverq** [comment]
Hi Ilya!

Thanks for the reply. I found the solution thanks to you and I want to share it.
I've made the [pull request](https://github.com/ilyalatt/Telega/pull/40)

**Comment by ilyalatt** [comment]
Hi! I've merged it. I will publish it to nuget soon. Thank you.

**Comment by ilyalatt** [comment]
Almost ready for publishing. But there is one problem. `SendMultiMedia` in `Telega.Example` throws `MEDIA_INVALID` error. If I try to send only photo or video it is ok. But it fails if both are attached.

**Comment by tarasverq** [comment]
> 
> 
> Almost ready for publishing. But there is one problem. `SendMultiMedia` in `Telega.Example` throws `MEDIA_INVALID` error. If I try to send only photo or video it is ok. But it fails if both are attached.

Have you tried the example from program.cs?

I've checked just now - it works fine
![Alt Text](https://i.imgur.com/h0fHoLU.png)

BTW I found that some videos can throw MEDIA_INVALID exception.  In this case I send them with [documentAttributeVideo](https://core.telegram.org/constructor/documentAttributeVideo), but you have to know the duration, and size of video.


My exapmle code
```
async Task<MessageMedia> UploadVideo(Some<InputPeer> peer, Video attachment)
{
    InputFile inputFile = await UploadAttachment(attachment);
    MessageMedia messageMedia = await _client.Messages.UploadMediaAsDocument(
        peer: peer,
        file: inputFile,
        attachment.MimeType,
        new Arr<DocumentAttribute>(new DocumentAttribute[]
        {
            new DocumentAttribute.VideoTag(
                false,
                true,
                attachment.Duration,
                attachment.Width,
                attachment.Height
            )
        })
    );
    return messageMedia;
}
```

**Comment by tarasverq** [comment]
And also i see that after update of Schema you set the _forceFile_ flag  in _UploadMediaAsPhoto_ method.
May be the problem is here.

**Comment by ilyalatt** [comment]
You're right. The new version 0.4.0 is published!
