### ISSUE TITLE
Any Standard for bracket?

### ISSUE THREAD

**Issue by GihanSoft** [ilyalatt/Telega#49]
you used this style every where:
```csharp
type MethodName(Args args) {
    //...
}
```
but changed `Dispose` mothod in #47 (commit 'doto') to this:
```csharp
public void Dispose()
{
    //....
}
```
please use standard. everywhere should be same style

**Comment by ilyalatt** [comment]
Hi! You did not read my message from your previous PR.

I use this style only for functions with arguments split across lines.

```
void F (int a, int b)
{
   ...
}

void F(
    int a,
    int b
) {
    ...
}
```

Can it be configured in .editorconfig?
If it can not be configured we'll follow the style with java-like braces at least for functions.

**Comment by GihanSoft** [comment]
I think it's not possible.
try this maybe you can export rider style
In Rider: File > Settings > Code Style > click Export button near "Enable EditorConfig support". Then if you want to change your code style settings, click Help > Find action (usually mapped to Ctrl-Shift-A) and type "Edit .editorconfig" (again, would be easier in next versions, I promise).

**Comment by ilyalatt** [comment]
Ok. It's easier to switch to java-like braces. I will try to find some time for it tomorrow.
