### ISSUE TITLE
IsAuthorized before connect

### ISSUE THREAD

**Issue by GihanSoft** [ilyalatt/Telega#50]
```csharp    
    var isAuth = new FileSessionStore(AppDomain.CurrentDomain.BaseDirectory + "session.dat")
        .Load()
        .Result
        .Match(s => s.IsAuthorized, () => false);
```
I used this but it stuck.

**Comment by ilyalatt** [comment]
You probably use it in WinForms or WPF app. You should not use `.Result`. You should use `await` to avoid deadlock.

**Comment by GihanSoft** [comment]
I can't. it's in constructor.

**Comment by ilyalatt** [comment]
You can use approach like

```
IsLoading = true;
(async () => {
    try {
        IsAuthorized = await ...
    }
    finally {
        IsLoading = false;
    }
})();
```

**Comment by GihanSoft** [comment]
this stuck too.

**Comment by ilyalatt** [comment]
Looks like `FileSessionStore` captures context. I'll fix it later. `Task.Run(store.Load)` should help because it runs the code in the thread pool.

**Comment by GihanSoft** [comment]
I used this:
```csharp
using var file = File.Open(
                    sessionPath,
                    FileMode.Open,
                    FileAccess.Read,
                    FileShare.ReadWrite);
                BinaryReader reader = new(file);
                IsAuthorized = Session.Deserialize(reader)?.IsAuthorized ?? false;
```

**Comment by ilyalatt** [comment]
I've added ConfigureAwait checker. Now there should be no context captures. Therefore no deadlocks even without `Task.Run`. Can you verify it please? I can publish a preview version if you prefer nuget package to latest master.
