### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ilyalatt** [ilyalatt/Telega#57]
Because of @GihanSoft recent activity I got interest to Telega. I wanted to simplify the public interface a long time ago. I realized that it is too hard for a lot of developers. Because of that some devs avoid the library. Now I feel that I can spend a few days to implement my plan. I want to gather what I made and what I want to make for the new release.

* simplified union tag access
* documentation prototype
* YAML-like DTO string representation (check out [this page](https://ilyalatt.github.io/Telega/docs/get-account-info))
* simplified auth for playground without config
* automatic dto generation without need of `./generate-dto.sh`
* Roslyn analyzer to force `ConfigureAwait(false)`
* `IReadOnlyList<T>` instead of `Arr<T>`
* `T?` instead of `Option<T>`
* `LanguageExt` dependency removal

**Comment by ilyalatt** [comment]
@tarasverq @GihanSoft
If you have any ideas about how to simplify Telega submit them here please

**Comment by GihanSoft** [comment]
Check function for still connection stable.

**Comment by GihanSoft** [comment]
Use SignInResult instead of exception.
Exceptions have impact that effect performance a lot.

**Comment by GihanSoft** [comment]
Set xml document in code for all public APIs. Start from Telegram Client.
And web document and guides.

**Comment by GihanSoft** [comment]
Use rasolyn addins for async that can be added with nuget (don't include in build, just compile time.) Can help fix async problems.

**Comment by GihanSoft** [comment]
Change Upload to IO or UpDowdLoad or File or something like that. Because it uses for download too.

**Comment by ilyalatt** [comment]
> Use SignInResult instead of exception.
> Exceptions have impact that effect performance a lot.

Performance is not critical on the sign in step. Much more CPU time is used for generating request. And a lot of time is just awaiting a call result. That's from pragmatic point of view.
From theoretical point of view there is `RpcResult` that resembles needed behavior. `CallUnsafe` can be introduced that creates exception but not throws it. `SignIn` can check an exception and return an error instead of throwing an exception.
But I am not sure because looks like it will complicate things more than needed.

**Comment by GihanSoft** [comment]
> > Use SignInResult instead of exception.
> > Exceptions have impact that effect performance a lot.
> 
> Performance is not critical on the sign in step. Much more CPU time is used for generating request. And a lot of time is just awaiting a call result. That's from pragmatic point of view.
> From theoretical point of view there is `RpcResult` that resembles needed behavior. `CallUnsafe` can be introduced that creates exception but not throws it. `SignIn` can check an exception and return an error instead of throwing an exception.
> But I am not sure because looks like it will complicate things more than needed.

Ok, if it's not easy, no problem

**Comment by tarasverq** [comment]
Hi everybody!

My wish list is:

1. Async version of Match methods
2. Public ctor for TelegaClient (not sure if it is acceptable in functional style)
3. ISessionStore with sessionKey in argument of Load method (I use more than one account at once, so I have to create SessionStore for each account)

**Comment by tarasverq** [comment]
One more request: parallel download and upload of file parts inside of `TelegramClientUpload` class.
It should increase the speed of downloading and uploading.

May be I'll do it if you don't mind?

**Comment by ilyalatt** [comment]
> One more request: parallel download and upload of file parts inside of `TelegramClientUpload` class.
> It should increase the speed of downloading and uploading.
> 
> May be I'll do it if you don't mind?

Yeah, Sure. You'll need to modify `DelayMiddleware`. Right now it puts all calls in a task queue. So it should ignore a task queue for file requests. Then you need to modify `TaskQueue` to allow `count` to be more than one. It will be used in Downloading/Uploading. Then you need to create a task queue with degree 4 for example and put calls in it. It will look like `fileRequests.Select(x => _taskQueue.Put(_tg.Call(x)))`.

**Comment by ilyalatt** [comment]
There is a lot of stuff that was planned and never happened. What is done is published under `v0.5.0`. The rest is moved to #80.
