### ISSUE TITLE
How cloud I answer the inline button send by bot 

### ISSUE THREAD

**Issue by Jycjmf** [ilyalatt/Telega#63]
Hi guys, I have already read the examples in Telega.Playground , but I did not find any example about reply to inline button like this:
![122629654-3f24bc80-d0f1-11eb-981c-bb879c47b2b5](https://user-images.githubusercontent.com/30173232/122680224-c6bd1900-d220-11eb-92d7-9fbf7da0428a.png)
I just want to use this library to click the button and get the message in the pop dialog like this:
![122629786-2963c700-d0f2-11eb-858f-93df09206657](https://user-images.githubusercontent.com/30173232/122680258-e05e6080-d220-11eb-8dc1-ee4cabe91765.png)
I have tried the TLSharp before , but it always throw exception. So I want to use this library instead . What should I do to make it ? Thanks!

**Comment by ilyalatt** [comment]
Hi! Telega generates RPC model based on tlscheme. You can look it [here](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/tl/api.tl). You're interested in part that starts with `---functions---`. There are a lot of functions. Looks like `messages.getBotCallbackAnswer` is the one you look for. It should look like `tg.Call(new GetBotCallbackAnswe(msgId: 123, data: button.Data, ...))`. To get this parameters you need to find message with buttons (there are examples in playground) and get `ReplyMarkup`. It should have `ReplyInlineMarkup` case. There are `KeyboardButton`s and you're interested in `KeyboardButtonCallback` case that have `Data`. The call result has optional `Message` property that you want to retrieve.

**Comment by Jycjmf** [comment]
> Hi! Telega generates RPC model based on tlscheme. You can look it [here](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/tl/api.tl). You're interested in part that starts with `---functions---`. There are a lot of functions. Looks like `messages.getBotCallbackAnswer` is the one you look for. It should look like `var answer = await tg.Call(new GetBotCallbackAnswer(msgId: 123, data: button.Data, ...))`. To get this parameters you need to find message with buttons (there are examples in playground) and get `ReplyMarkup`. It should have `ReplyInlineMarkup` case. There are `KeyboardButton`s and you're interested in `KeyboardButtonCallback` case that have `Data`. To get the message use `answer.Message`.

Thanks bro , I have solved it .

**Comment by ilyalatt** [comment]
@Jycjmf can you add your solution to playground?

**Comment by Jycjmf** [comment]
> @Jycjmf can you add your solution to playground?

sorry bro , I changed to TDSharp instead , I cloud shared it if you dont mind it.

**Comment by ilyalatt** [comment]
Yeah, it should be helpful if you share the solution anyway.

**Comment by Jycjmf** [comment]
> Yeah, it should be helpful if you share the solution anyway.
OK , here are the code works in TDSharp
```
     public static async void GetChannels(long offsetOrder = long.MaxValue, long offsetId = 0, int limit = 1000)
        {
            var chats = await _client.ExecuteAsync(new TdApi.GetChats
            { OffsetOrder = offsetOrder, Limit = limit, OffsetChatId = offsetId });
            foreach (var chatId in chats.ChatIds)
            {
                var chat = await _client.ExecuteAsync(new TdApi.GetChat { ChatId = chatId });
                    var res = _client.GetChatHistoryAsync(chat.Id, long.MaxValue,0, 30, false).Result.Messages_
                        .Where(x => x.ReplyMarkup != null);

                    var KeyboardData = (TdApi.ReplyMarkup.ReplyMarkupInlineKeyboard)res.First().ReplyMarkup;
                    foreach (var each in KeyboardData.Rows)
                    {
                        var buttonData =
                            (TdApi.InlineKeyboardButtonType.InlineKeyboardButtonTypeCallback)each.First().Type;
                        var payload = new TdApi.CallbackQueryPayload.CallbackQueryPayloadData();
                        payload.Data = buttonData.Data;
                        var buttonContent =
                            await TdApi.GetCallbackQueryAnswerAsync(_client, chatId, res.First().Id, payload);
                        Console.WriteLine(buttonContent.Text + "  " + buttonContent.Url);
                    }

                    Console.WriteLine(res.First().Content);
                }
            
        }
```
